server.port=9082
server.address=localhost
serverId=server3
grpc.port=10082
spring.datasource.url=jdbc:h2:file:/tmp/hellohello-server3

zkConnectString=localhost:2181
zkNamespace=
superPass=superpass123
token.secret=secret123

zookeeper.session.timeout=5000
zookeeper.connection.timeout=5000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
logging.level.edu.sjsu.cmpe172.hellohello=INFO

spring.main.allow-circular-references=true