server.port=9081
server.address=localhost
myDescription=server2 instance
grpc.port=10081
spring.datasource.url=jdbc:h2:file:/tmp/hellohello-server2

zkConnectString=localhost:2181
zkNamespace=
superPass=superpass123
token.secret=secret123

zookeeper.session.timeout=5000
zookeeper.connection.timeout=5000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
logging.level.edu.sjsu.cmpe172.hellohello=INFO

spring.main.allow-circular-references=true